### ISSUE TITLE
Ceph: get_bucket_list does not work. If empty or error when get_bucket_list just set up the wanted bucket name

### ISSUE THREAD

**Issue by victormachadoperez** [dirkpetersen/froster#104]

**Comment by dirkpetersen** [comment]
This is with froster v0.14.18
- Ceph does not really have a region, claude says the default region for ceph is us-east-1 (just as it is for AWS) 
- If no bucket list returns it should be simply "enter bucket name" regardless if new or existing bucket 

[?] Choose your profile:
   default-inactive
   aws
   dpcri
 > rgw
   dipeit
   + Create new profile


*** SET REGION ***

[?] Choose your region:
 > -- no region --
   + Create new region


*** SET ENDPOINT ***

[?] Enter the Ceph endpoint: https://rgw.ohsu.edu

Checking credentials...

  Profile: rgw
  Provider: Ceph
  Endpoint: https://rgw.ohsu.edu

...credentials are valid


*** SET S3 ***

[?] Choose your s3 bucket:
 > + Create new bucket

[?] Enter new bucket name: dpcribucket1

Creating bucket dpcribucket1...

Error
  File: froster.py
  Function: _make_api_call
  Line: 1548
  Error code:
  Exception type: ClientError

If you thing this is a bug, please report this to froster developers at: https://github.com/dirkpetersen/froster/issues

Could not create bucket dpcribucket1

**Comment by victormachadoperez** [comment]
So the leanest solution has been to add the "Enter bucket name" in case the provider is Ceph.
"Enter bucket name" and "Create new bucket" will always be shown for Ceph regardless of whether the bucket list is retrieved from the Ceph server.

This is implemented in froster v0.16.1
