### ISSUE TITLE
EC2 idle shutdown best practices 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#11]
Users are often scared to leave cloud instances running which can hamper cloud adoption. Froster has an experimental idle detection which lets ec2 instances self-terminate after a few days (72 hours by default). It has a monitoring cron job in systemd that is run hourly and if this cron job has detected an idle state 72 consecutive times the machine will be terminated.

Is this a reasonable approach for Amazon Linux 2003? 

function AWSBoto._monitor_is_idle: 
https://github.com/dirkpetersen/froster/blob/main/froster.py#L3915

**Comment by victormachadoperez** [comment]
For future development
