### ISSUE TITLE
profiles not providers 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#115]
@victormachadoperez, the new version 0.15.1 looks much better. However it is now configuring providers but should be configuring profiles. With the current approach it seems you can only have one AWS profile and one Ceph profile but in fact people may have multiple profiles , especially with AWS configs and multiple Ceph clusters. I think the config should look more similar to this and froster should have a --profile option as it used to have.

[S3]
profile = aws-dp

[profile aws-dp]
provider = AWS
bucket_name = froster-dpcri
archive_dir = froster
storage_class = INTELLIGENT_TIERING

**Comment by victormachadoperez** [comment]
I misunderstood the profile/provider nuance. 
I always considered the AWS profile (credentials/config) when speaking about profiles.
Also, I didn't consider that someone would have multiple profiles for the same provider.
I'll take a look.

**Comment by victormachadoperez** [comment]
Implemented in Froster v0.16.0
