### ISSUE TITLE
banner questions 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#132]
Thanks for putting in the Banner @victormachadoperez . I had hoped we could have a banner on test case, test case coverage / number of successful test cases. Also, can you clarify : is the minimum Python version 3.9 or 3.8 ?

**Comment by victormachadoperez** [comment]
There was a typo on the pyproject.toml configuration file. 
It was set to python = "^3.8.1"; therefore, scaping version 3.8.

It is now fixed
