### ISSUE TITLE
curl | bash is bad 

### ISSUE THREAD

**Issue by ivan-avalos** [dirkpetersen/froster#14]
```sh
curl https://raw.githubusercontent.com/dirkpetersen/froster/main/install.sh | bash
```

Please no. Piping directly to `bash` is not okay, if network fails, you'll get a corrupted installation. In general, it is not a good practice to do this for many other reasons. I advice you to update it to:

```sh
curl -O https://raw.githubusercontent.com/dirkpetersen/froster/main/install.sh
bash install.sh
```

A warning that advices the user to read the script before running it would be even better!

**Comment by dirkpetersen** [comment]
Piping to bash has a bad reputation (ChatGPT agrees with you) but in practice it makes really no difference. If you get a corrupted install you can just run it again (so far, knock on wood, did not happen to me in 15 years of Github) and the download, review first then execute paradigm is nice in theory but < 1% of the users check this before they are running something and they can still do this by leaving out the pipe to bash thing.

**Comment by dirkpetersen** [comment]
closing
