### ISSUE TITLE
moving config and code to ~/.froster

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#22]
We have been discussing to move code and configs to ~/.froster but looking into this a bit more we need to learn more about the benefits of this move and the best practice approach here. I had not done much research and basically looked at how the python community does it. I learned about the XDG base directory and it seems it was created to avoid clutter in the home directory, a goal I can very much subscribe to:

https://maex.me/2019/12/the-power-of-the-xdg-base-directory-specification/
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html 

In general there are always many “standards” and / or best practices and multiple people propose different things but in this case Lennart Poettering in addition to the Python community is also subscribing to this goal so I think it carries a lot of weight but it is possible that there are other standards. One thing to note is that we want to also avoid adding to many folders to PATH so the scripts should always end up in ~/.local/bin

**Comment by victormachadoperez** [comment]
I agree with the XDG Base Directory Specification. It is true that having all the code in the same directory under your $HOME directory 'simplifies' file management, but at the expense of other aspects, such as cluttering $HOME. I believe that the benefits of implementing XDG specifications outweigh the costs, even when using the basics as the article mentioned.

**Comment by victormachadoperez** [comment]
Also I will consider the Python Packaging user guide for cmd standalone applications: 
[https://packaging.python.org/en/latest/guides/installing-stand-alone-command-line-tools/](https://packaging.python.org/en/latest/guides/installing-stand-alone-command-line-tools/)

**Comment by dirkpetersen** [comment]
looking at pipx is a good idea. The only downside is added complexity, researchers are comfortable with a low tech approach of using the shell wrapper that invokes python for them, they can easily modify the behavior as no extra package management strategy is required. One the other hand,  it looks quite a bit non-standard for Python developers which is not good

**Comment by victormachadoperez** [comment]
If we want Froster to be standalone, reliable, durable, and easy to maintain, we need to stick to the standards as much as we can (you were absolutely right in pointing out the XDG Base Directory Standards).

The standard in Python for standalone applications is to use pipx.

I have developed this concept in the branch: [https://github.com/HPCNow/froster/tree/OHSU-63-froster-as-python-package](https://github.com/HPCNow/froster/tree/OHSU-63-froster-as-python-package). You can read the README.md file there with the installation instructions.

The main concepts are:

- Prerequisite packages need to be installed before installing Froster. Separate instructions for different architectures.
- As rclone is a commercial tool, the best practice here would be to install it as a prerequisite using their installation instructions. Then, we don't need to worry about downloading binaries by architecture and repeating the process for updates. Also, many researchers could potentially already be using rclone, so maybe it's already installed on their system.
- ```pipx``` is in charge of installing/uninstalling Froster.
- Installation is configured in the [setup.py](https://github.com/HPCNow/froster/blob/OHSU-63-froster-as-python-package/setup.py) file, which is easy to read/understand.
- Froster is installed directly from the GitHub repository: ```pipx install git+https://github.com/HPCNow/froster.git@OHSU-63-froster-as-python-package```.
- In the future, GitHub actions could automatically upload the project package to a Python package repository (like: [PyPi](https://pypi.org/)) and the installation command would become: ```pipx install froster```.
- ```pipx``` installs Froster and its dependencies in a virtual environment and ensures that ```~/.local/bin``` is in PATH and there is a Froster symlink there.
- The ```pwalk``` project is added as a git submodule, and the [setup.py](https://github.com/HPCNow/froster/blob/OHSU-63-froster-as-python-package/setup.py) is in charge of downloading/compiling/moving the ```pwalk``` tool to the right place.

If you agree with these methods, I will merge this into our main branch.

**Comment by dirkpetersen** [comment]
It sounds great to me to shift most of the heavy lifting to pipx installer, including sub-module for pwalk. However, one of the key design goals is for me to have a single command install as the default installer (The key audience is scientists and not developers and they often don't read the pre-reqs). rclone is commercial open source and must be installed as part of this process as older versions are often installed but have shortcomings.  For example the default version installed in our network is multiple years old and does not support fuse3 (for mounting) which is a requirement for later versions and we cannot test against multiple libraries. We only need ARM64 and X84-64 as other platforms are not relevant at this time, so one could perhaps detect ARM and if it is not ARM we assume X86-X64 (no need for 32 bit platforms) 

Perhaps this would be the best path forward: 

- default install remains shell script that ensures that pipx is installed and drives pipx, if it fails print url to pre-requisites and developer install 
- developer install is pipx with prereqs (I like the fact that froster will be registered in pypi, this gives additional visibility 

how would "froster update" be handled? 

Also one of my colleagues is using this approach  https://github.com/moloney/byoe/blob/main/bootstrap-no-sys-python.sh if no python3 with a minimum version be can be found and cannot be loaded through the module system. https://gregoryszorc.com/docs/python-build-standalone/main/ .  This could be an additional option also for example as a failure 
mode if the default python on the system has a sufficient version but no pip installed.  This has been a failure mode on some systems as (sadly) the default python version on RHEL8 is still python 3.6 and the distributions sometimes offer pip as as addon package (python3-pip) and not integrated in python as it should have been since v 3.4. If I understood correctly, pip is a requirement to install pipx on older systems.

**Comment by victormachadoperez** [comment]
Ok, let's do this: 

- An ```install.sh``` script will handle the pre-requisite checks and the installation of froster via ```pipx install froster``` command.
- When a pre-requisite is not met, the script will prompt the user to run the command for install the missing package.
- Froster will be deployed as a PyPi package by a Github Actions pipeline after all tests passed.
- rclone will be downloaded and installed inside the Froster environtment. Froster will always use the downloaded version to avoid collision with older rclone installs
- Froster update will be handled by pipx itself using the command ```pipx upgrade froster```. I don't think that a package can self update in running time (I'll look into this). Following the same approach a for checking rclone updates, a message could be prompted to the user to run ```pipx upgrade froster``` to update the package (no ```sudo``` command needed)
