### ISSUE TITLE
check for update 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#23]
Add a feature where froster checks every x days if there is an update for froster on github (or one of the dependencies pwalk or rclone). If there is an update, prompt the user to run "froster update" to update to the latest version of froster. Do not check for updates of pwalk or rclone independent of the of the deterministic configurations in froster.

**Comment by victormachadoperez** [comment]
Updating third-party tools should happen alongside a new Froster release. Doing it separately could mess with compatibility.

One way to handle updates is to set up a cron job.

Another option is to check for updates after each command. We could use curl or wget to quickly see if there's a new Froster version available (I'll look into this). Then, we can prompt users to update by running "froster update," or they can snooze the message for a few days. This way, Froster stays in control without relying solely on a cron job.

**Comment by dirkpetersen** [comment]
or perhaps check every 7 days or more or so froster is invoked. One could track some lastchecked entry in the local config and compare against some config file that contains the lastest version info in https://github.com/dirkpetersen/froster/blob/main/ ?

**Comment by dirkpetersen** [comment]
HPC admins frown a bit on cron jobs if executed on login nodes

**Comment by victormachadoperez** [comment]
I thing the best way to accomplish this would be the following:

- After each command, check the timestamp of the last time we checked for an rclone update.
- Compare the stored timestamp with current timestamp to see if we need to check for an rclone update. Then:
  - If there is an update available, then update rclone.
  - Store the current timestamp in the local config

**Comment by dirkpetersen** [comment]
OK, sounds great, let's do that
