### ISSUE TITLE
end user prompts to sudo

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#24]
When offering prompts to users to sudo (for example to install a missing dependency) we need to consider 3 different scenarios:

- users running on Debian/Ubuntu machine (apt install) on which they have admin access
- users running on RHEL (e.g. rocky) machine (dnf install) on which they have admin access
- users running on HPC machine on which they have no access to the package manager 

users should get the appropriate message of what to do, for example for HPC users : " Please contact administrator"

**Comment by victormachadoperez** [comment]
Noted. 

Are there any other main OS Froster should support like CentOS, macOS? Or software package management system like brew?

**Comment by dirkpetersen** [comment]
Since CentOS8 people have pretty much given up on it i think, most people use rocky and alma as they are RHEL compatible. I think there is really no business case for having it run on Windows or Mac as one does typically not manage huge datasets on these systems and perhaps we should exclude others more aggressively here: https://github.com/dirkpetersen/froster/blob/main/froster.py#L12

**Comment by victormachadoperez** [comment]
If we agree on the installation method of Froster on issue #22, then the sudo commands will be run in the pre-requisite installation steps. No more sudo prompts for end user.
