### ISSUE TITLE
monitor email address

### ISSUE THREAD

**Issue by victormachadoperez** [dirkpetersen/froster#26]
There is a command for monitoring  
```froster config --monitor <email>```
The user configuration for froster includes the user name and the user email. 
 
The <email> in ```froster config --monitor <email>``` could be different from the configured user email?

**Comment by dirkpetersen** [comment]
no it should be the same, it is just configured on the cli as it is only used in an ec2 instance that has been deployed with --aws. There is not a full config available on the cloud machine, hence the cli option ..... could also be solved by transferring the config to ec2
