### ISSUE TITLE
test.sh - No such file or directory

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#69]
[dp@box2 froster]$ ./tests.sh
Test data folder: /tmp/froster.KIj
Using test bucket froster-bvcxa
./tests.sh: line 93: /home/users/dp/.config/froster/general/bucket: No such file or directory

**Comment by victormachadoperez** [comment]
In froster v0.16.12 a new command has been added: "froster test"

This command tests the basic functionality of froster: 
- Authenticate via credentials
- Creates a bucket
- Generates dummy data
- Index dummy data
- Archive dummy data
- Delete dummy data
- Clean up: delete generated bucket and dummy data
