### ISSUE TITLE
froster index issue

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#70]
[peterdir@exahead2 froster]$ froster index /home/dp/csvs

Error
  File: froster.py
  Function: index
  Line: 3289
  Error code: Archiver._slurm_cmd() missing 1 required positional argument: 'scheduled'

If you thing this is a bug, please report this to froster developers at: https://github.com/dirkpetersen/froster/issues

**Comment by victormachadoperez** [comment]
Fixed in froster v0.12.28. 
Already available in Github and PyPi.
