### ISSUE TITLE
froster update error 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#79]
on my local wsl machine 

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
```

froster updates correctly to the latest version v0.12.32

but when i run update again, I get this 

```
dp@grammy:~$ froster update

Error
  File: froster.py
  Function: subcmd_update
  Line: 6678
  Error code: 0

If you thing this is a bug, please report this to froster developers at: https://github.com/dirkpetersen/froster/issues

```

on our RHEL HPC system it works and I get this: 

```
froster update

Froster is up to date: froster v0.12.32
```

The difference between the HPC environement and my local environment is that my local environment has a compatible python at /usr/bin/python3 and HPC does not.

However, the current python I use is different than the python3.9 version that is /usr/bin/python3

```
$ which python3
/home/dp/.rye/shims/python3
dp@grammy:~$
dp@grammy:~$
dp@grammy:~$ python3 --version
Python 3.10.14
```

not sure if root cause but a hint 

deleting ~/.config/froster and reinstalling does not help

**Comment by victormachadoperez** [comment]
This is solved in froster v0.14.15
