### ISSUE TITLE
HPC install not supported 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#84]
@victormachadoperez , I just tried this on a new install and we cannot expect that than an HPC sysadm will have pipx installed, we need to find a different solution, either run `python3 -m pip install --user --upgrade pipx` (with Python 3.12 and newer you need to run `python3 -m pip install --break-system-packages --user --upgrade pipx`) or use the zipapp releases https://github.com/pypa/pipx/releases 

also RHEL does not have `apt`.  Please remove references to apt or implement solution that detects os such as this one: https://github.com/dirkpetersen/asm/blob/main/asm.py#L3653 and then use dnf or apt . If slurm is installed, assume that the the user will never have have access to sudo. 

```
curl -s https://raw.githubusercontent.com/dirkpetersen/froster/main/install.sh?$(date +%s) | bash
Error: pipx is not installed.

Please install pipx
In most linux distros you can install the latest version of pipx by running the following commands:
  sudo apt update
  sudo apt install -y pipx
  pipx ensurepath

Error: exit: exit code 1

Rolling back installation...
...done
```

**Comment by victormachadoperez** [comment]
Updated instructions for RHEL dependencies check
pipx is now installed via python3 -m pip install --user --upgrade pipx (as other options are not safe and may broke the python environment)

This is solved in froster v0.14.15
