### ISSUE TITLE
support hundreds of buckets 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#91]
Some people have hundreds of buckets which may not work well with an interactive config like Froster, perhaps we limit the list of buckets that can be displayed to 50 ish and move the "Create new bucket to the top?"

![image](https://github.com/dirkpetersen/froster/assets/1427719/1a6fbe5b-61ca-4ab9-a6f5-c27098e89ed6)

**Comment by victormachadoperez** [comment]
Solved in froster v0.14.18
