### ISSUE TITLE
froster archive -- return to previous behavior 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#92]
currently i need to invoke -H to see hotspot files 

```
froster archive -H
```

and after that I see 

```
[?] How should we proceed with the archiving process?:
   Archive all hotspots
   Archive one hotspot
 > Cancel
```

this is not a good default behavior as people should never just be able archive everything with one click .... that is the purpose of the `--larger xxx --older xxx`  option. This should happen: 

```
froster archive 
```

- check if there this a hotspots file. If there is one, open that file and show all the hotspots, If there is more than 1 hotspots file open athe list of files and let the user pick one 

- if there is no hotspots file give the user the error message that is already great: 

```
No hotposts found.

You can search for hotspot by indexing folders using command:
    froster index "/your/folder/to/index"

For archive a specific folder run:
    froster archive "/your/folder/to/archive"
```

**Comment by victormachadoperez** [comment]
Even if only there is one I'll make the user select the hotspot file so it simplifies development and make the user aware of what he is doing.

Solved in froster v0.14.16
